-- 코드를 입력하세요
-- SELECT TO_CHAR(PUBLISHED_DATE, 'YYYY-MM'), COUNT(*)
-- FROM BOOK
-- GROUP BY TO_CHAR(PUBLISHED_DATE, 'YYYY-MM')
-- ORDER BY TO_CHAR(PUBLISHED_DATE, 'YYYY-MM');


-- GROUP BY TO_CHAR(B.SALES_DATE, 'YYYY-MM')
-- ORDER BY TO_CHAR(B.SALES_DATE, 'YYYY-MM');

SELECT A.CATEGORY AS CATEGOTY, SUM(B.SALES) AS TOTAL_SALES
FROM BOOK A
FULL OUTER JOIN BOOK_SALES B
ON A.BOOK_ID = B.BOOK_ID
WHERE TO_CHAR(B.SALES_DATE,'YYYY-MM')='2022-01'
GROUP BY A.CATEGORY
ORDER BY A.CATEGORY;